function getFileUrl(file){
    return chrome.runtime.getURL(file)
}

var EmojisData = [
    [getFileUrl("images/meow.svg"),' _meow_ ','meow cat head cute hey :D hello hi'],
    [getFileUrl("images/gobo.svg"),' _gobo_ ','gobo head cute hey :D hello hi baby'],
    [getFileUrl("images/waffle.svg"),' _waffle_ ','food waffle yummy'],
    [getFileUrl("images/taco.svg"),' _taco_ ','food taco yummy burger'],
    [getFileUrl("images/sushi.svg"),' _sushi_ ','food sushi japan yummy'],
    [getFileUrl("images/pizza.svg"),' _pizza_ ','food pizza italy yummy'],
    [getFileUrl("images/candycorn.svg"),' _candycorn_ ','food candycorn halloween egg yummy'],
    [getFileUrl("images/apple.svg"),' _apple_ ','food apple fruit healthy plant yummy'],
    [getFileUrl("images/cupcake.svg"),' _cupcake_ ','food cupcake yummy'],
    [getFileUrl("images/easter_eggs/cat.png"),' _:)_ ','OuO cat head cute'],
    [getFileUrl("images/easter_eggs/aww-cat.png"),' _:D_ ','happy :D cat delighted head cute baby excited touched'],
    [getFileUrl("images/easter_eggs/cool-cat.png"),' _B)_ ','cat cool guy sunglasses head gg lol haha nice cute'],
    [getFileUrl("images/easter_eggs/tongue-out-cat.png"),' _:P_ ','cat tongue out taste yummy eyes closed happy head cute'],
    [getFileUrl("images/easter_eggs/wink-cat.png"),' _;P_ ','wink blink tongue cat happy delighted head cute'],
    [getFileUrl("images/easter_eggs/lol-cat.png")," _:'P_ ",'cat lol xD XD xd funny laughing haha tears head cry cute '],
    [getFileUrl("images/easter_eggs/upside-down-cat.png"),' _P:_ ','upside-down-cat tongue head cute'],
    [getFileUrl("images/easter_eggs/fav-it-cat.png"),' _**_ ','favourite stars cat wow project head cute excited yay'],
    [getFileUrl("images/easter_eggs/pizza-cat.png"),' _:D<_ ','food pizza cat happy eating head cute yummy'],
    [getFileUrl("images/easter_eggs/love-it-cat.png"),' _<3_ ','love-it-cat happy heart red lovely project head cute excited yay fire'],
    [getFileUrl("images/easter_eggs/rainbow-cat.png"),' _:))_ ','happy delighted cat rainbow colorful colourful haha head cute'],
    [getFileUrl("images/easter_eggs/huh-cat.png"),' _:3_ ','cat hmm huh what? head cute jealous ;-; :3 quite bruh'],
    [getFileUrl("images/broccoli.svg"),' _broccoli_ ','food broccoli vegetables healthy green plant yummy'],
    [getFileUrl("images/camera.svg"),' _camera_ ','travel digital camera photo view'],
    [getFileUrl("images/compass.svg"),' _compass_ ','travel compass directions'],
    [getFileUrl("images/suitcase.svg"),' _suitcase_ ','travel suitcase work business bag'],
    [getFileUrl("images/map.svg"),' _map_ ','travel map position hotspot paper'],
    [getFileUrl("images/binoculars.svg"),' _binoculars_ ','travel binoculars view glasses'],
    [getFileUrl("images/10mil.svg"),' _10mil_ ','10mil congrats congratulations yay :D woah confetti'],
    [getFileUrl("images/pride.svg"),' _pride_ ','flag pride colorful colourful rainbow blm black lives matter'],
    [getFileUrl("images/blm.svg"),' _blm_ ','blm black lives matter hands fists protest'],
    ["",'⌚️','⌚️ clock time'],
    ["",'⏰','⏰ alarm clock morning time'],
    ["",'⏱','⏱️ clock stopwatch time'],
    ["",'⏲','⏲️ clock time'],
    ["",'⌨','⌨️ keyboard computer buttons'],
    ["",'☎️','☎️ telephone call ring red'],
    ["",'⌛️','⌛️ funnel time sand'],
    ["",'⚖️','⚖️ scales balance weight golden fair'],
    ["",'⚙️','⚙️ gear settings iron tool'],
    ["",'✉️','✉️ envelope mail notifications paper'],
    ["",'✂️','✂️ scissors stationery sharp tool'],
    ["",'✒️','✒️ black nib scaler tool stationery pen work sharp'],
    ["",'☂️','☂️ purple rain umbrella wet'],
    ["",'✏️','✏️ pencil stationery work'],
    ["",'☕️','☕️ coffee tea cup hot drinks work relax'],
    ["",'♟️','♟️ european chess'],
    ["",'⚰️','⚰️ brown coffin'],
    ["",'⚱️','⚱️ golden vase expensive'],
    ["",'⛏️','⛏️ pick axe hammer tool iron hard heavy'],
    ["",'⚔️','⚔️swords daggers knife knight ninja weapon fight'],
    ["",'⚒️','⚒️ hammer iron heavy tool'],
    ["",'⛓️','⛓️ chains iron lock'],
    ["",'⚗️','⚗️ alembic water aquarium goldfish glass bowl tank'],
    ["",'⛑️','⛑️ safety helmet hat health hp equipment'],
    ["",'⭐️','⭐️ star favourite shape yellow'],
    ["",'✨','✨ sparkles stars colorful bright'],
    ["",'⚡️','⚡️ lightning thunderstorm rain electrical power weather nature'],
    ["",'☄️','☄️ meteor fire flame rock nature'],
    ["",'☀️','☀️sunny yellow brightweather weather nature'],
    ["",'⛅️','⛅️rainy showers cloudy sun weather nature'],
    ["",'☁️','☁️ cloudy nature weather sad'],
    ["",'⛈️','⛈️ raining cloudy weather sad bad nature thunder'],
    ["",'⛄️','⛄️ snowman christmas cold decoration weather nature snowy'],
    ["",'❄️','❄️ snowflake christmas cold nature weather snowy'],
    ["",'☔️','☔️umbrella rainy nature weather'],
    ["",'☘️','☘️ nature green leaf life'],
    ["",'☹️','☹️ sad bad upset :( head'],
    ["",'✌️','✌️ yay yes happy 2 two v hand fingers'],
    ["",'☝️','☝️ this one hand point fingers'],
    ["",'✍️','✍️ writing hand pencil pen fingers work'],
    ["",'✋','✋ raise hand stop bye wave'],
    ["",'☺️','☺️ head smile happy :)'],
    ["",'⚽️','⚽️ sports soccer football'],
    ["",'⚾️','⚾️ sports tennis ball'],
    ["",'⛳️','⛳️ golf flag hill sports'],
    ["",'⛹️','⛹️ basketball guy sporty'],
    ["",'⛷️','⛷️ iceskating man sports guy sporty'],
    ["",'⛸️','⛸️ shoes iceskating sporty equipment roller skates'],
    ["",'✈️','✈️ aeroplane flight travel transportation'],
    ["",'⛵️','⛵️ sailboat sports transportation ship sea'],
    ["",'Ⓜ','Ⓜ️ m M logo cyan'],
    ["",'⚓️','⚓️ anchor sailer ship boat transportation sea'],
    ["",'⛽️','⛽️fuel pump gas station orange'],
    ["",'⛲️','⛲️ fountain water bowl'],
    ["",'⛺️','⛺️ camping hiking mountains hills '],
    ["",'⛪️','⛪️ school home building church'],
    ["",'⛰️','⛰️ mountains hills everest nature'],
    ["",'⛱️','⛱️ beach sand umbrella holiday weather'],
    ["",'⛴️','⛴️ ferry transportation ship boat sea'],
    ["",'⛩️','⛩️ shinto shrine arch red door'],
    ["",'♨️','♨️ hot heat coffee drink'],
    ["",'❗️','❗️ danger alert be careful exclamation mark punctuations !'],
    ["",'❕','❕ danger alert be careful exclamation mark punctuations !'],
    ["",'❓','❓ question mark what why ? punctuations'],
    ["",'❔','❔ question mark what why ? punctuations'],
    ["",'©','©️ copyright cooperation'],
    ["",'®','®️ registered trademark symbol'],
    ["",'‼','‼️ punctuations exclamation marks'],
    ["",'⁉','⁉️ punctuations exclamation mark what why ? question mark huh !'],
    ["",'™','™️ tm trade mark'],
    ["",'➕','➕ plus addition maths'],
    ["",'➖','➖ minus subtraction maths'],
    ["",'➗','➗ division divide maths'],
    ["",'✖️','✖️ times multiplication maths cross wrong fail'],
    ["",'⛔','⛔ stop access denied warning sign'],
    ["",'⭕','⭕circle correct go sign'],
    ["",'❌','❌ cross wrong fail sign exam'],
    ["",'✔️','✔️ correct green mark sign tick exam'],
    ["",'〰','〰️ stocks steady stable linee wire'],
    ["",'〽','〽️ stocks rise and fall line'],
    ["",'⚠️','⚠️ sign alert be careful dangerous yellow !'],
    ["",'☑️','☑️ correct green mark sign tick blue square'],
    ["",'✅','✅ correct green mark sign tick square'],
    ["",'❎','❎ cross wrong fail sign green square'],
    ["",'▶','▶️ video music play square resume arrows'],
    ["",'⏩','⏩ next song music video square arrows skip'],
    ["",'⏪','⏪ video song music previous back arrows skip'],
    ["",'⏫','⏫ upper video song music arrows skip'],
    ["",'⏬','⏬ downwards video song music arrows skip'],
    ["",'ℹ','ℹ️ information more'],
    ["",'⏭','⏭️ next song music video square end jump arrows skip'],
    ["",'⏮','⏮️ previous song music video square start jump arrows skip'],
    ["",'⏯','⏯️ pause play video song music arrows skip square'],
    ["",'⏏','⏏️ arrows up skip square'],
    ["",'◀','◀️ arrows left square'],
    ["",'➡','➡ arrows right square'],
    ["",'⬅','⬅️ arrows left square'],
    ["",'⬆','⬆️ arrows up square'],
    ["",'⬇','⬇️ arrows down square'],
    ["",'↗','↗️ upper right arrow'],
    ["",'↘','↘️ lower right arrow'],
    ["",'↙','↙️ lower left arrow'],
    ["",'↖','↖️ upper left arrow'],
    ["",'↪','↪️ back undo redo arrow square'],
    ["",'↩','↩️ back undo redo arrow square'],
    ["",'⤴','⤴️ up arrow square'],
    ["",'⤵','⤵️ down arrow square'],
    ["",'✳️','✳️ star asterisk green square'],
    ["",'✴️','✴️ sparkle explosive orange square'],
    ["",'❇️','❇️ green square sun bright light shine'],
    ["",'㊗','㊗️ wish zhu red warning chinese word circle'],
    ["",'㊙','㊙️ secret red warning chinese word circle'],
    ["",'⚕️','⚕️ medic square'],
    ["",'☦️','☦️ orthodox cross square'],
    ["",'♾️','♾️ infinite n 8 square'],
    ["",'⚛️','⚛️ atom chemistry square'],
    ["",'⛎️','⛎️ ophiuchus square purple constellation'],
    ["",'✝️','✝️ christian square'],
    ["",'☪️','☪️ star and crescent moon square singapore'],
    ["",'☮️','☮️ peace square'],
    ["",'☯️','☯️ chinese yinyang square'],
    ["",'☸️','☸️ wheel of dharma square'],
    ["",'♈️','♈️ aries square purple constellation'],
    ["",'♉️','♉️ taurus square purple constellation'],
    ["",'♊️','♊️ gemini square purple constellation'],
    ["",'♋️','♋️ cancer square purple constellation'],
    ["",'♌️','♌️ leo square purple constellation'],
    ["",'♍️','♍️ virgo square purple constellation'],
    ["",'♎️','♎️ libra square purple constellation'],
    ["",'♏️','♏️ scorpius square purple constellation'],
    ["",'♐️','♐️ sagittarius square purple constellation'],
    ["",'♑️','♑️ capricorn square purple constellation'],
    ["",'♒️','♒️ aquarius square purple constellation'],
    ["",'♓️','♓️ pisces square purple constellation'],
    ["",'❤️','❤️ heart love red fire'],
    ["",'❣️','❣️ heart love red fire punctuation exclamation mark !'],
    ["",'♠️','♠️ pips sword poke cards black symbol'],
    ["",'♣️','♣️ pips club poke cards black symbol'],
    ["",'♥️','♥️ pips heart love poke cards black'],
    ["",'♦️','♦️ pips black diamond poke cards'],
    ["",'♀️','♀️ girl female symbol gender'],
    ["",'♂️','♂️ gender boy masculine symbol'],
    ["",'♻️','♻️ green environmentally friendly recycle'],
    ["",'☢️','☢️ radioactive hazard dangerous warning symbol'],
    ["",'☣️','☣️ biohazard warning symbol dangerous'],
    ["",'⚜️','⚜️ fleur-de-lis decoration badge scouts'],
    ["",'➰️','➰️ curly loop blue line'],
    ["",'➿️','➿️ double curly loop blue line square '],
    ["",'☠️','☠️ toxic dangerous skull skeleton die death dead bones'],
    ["",'⬛','⬛️ black square shape'],
    ["",'⬜','⬜️ white square shape'],
    ["",'⚪️','⚪️ white circle shape'],
    ["",'⚫️','⚫️ black circle shape'],
    ["",'▪','▪️ square solid black shape'],
    ["",'▫','▫️ square hollow shape'],
    ["",'◻','◻️ white square shape'],
    ["",'◽','◽️ white square solid shape'],
    ["",'◾','◾️ black square solid shape'],
    ["",' (◕‿◕✿) ','(◕‿◕✿) flower girl happy'],
    ["",' (づ￣ ³￣)づ ','(づ￣ ³￣)づ love kiss'],
    ["",' (⁄ ⁄•⁄ω⁄•⁄ ⁄) ','(⁄ ⁄•⁄ω⁄•⁄ ⁄) shy embarrassed cute happy'],
    ["",' ( ་ − ་ )ུ ','( ་ − ་ )ུ phew disagree dissapointed hmm not good'],
    ["",' ( ༎ຶ ۝ ༎ຶ ) ','( ༎ຶ ۝ ༎ຶ ) sad crying tears bad'],
    ["",' ( う-´)づ︻╦̵̵̿╤──   (˚☐˚”)/ ','( う-´)づ︻╦̵̵̿╤──   (˚☐˚”)/ gun shooting scary death die sniper shocked'],
    ["",' _(┐「ε:)_ ','_(┐「ε:)_ lying on the ground dead give up'],
    ["",' ʕ ·(エ)· ʔ ','ʕ ·(エ)· ʔ cute little teddy bear'],
    ["",' (⊚︷⊚) ','(⊚︷⊚) spooky glasses angry bad mad big eyes'],
    ["",' ~(￣▽￣)~ ','~(￣▽￣)~ relaxed happy lazy comfortable'],
    ["",' O(∩_∩)O ','O(∩_∩)O happy headphone guy headset listening music'],
    ["",' ٩( ‘ω’  )و ','٩( ‘ω’  )و cute happy dog puppy'],
    ["",' ★ ','★ star'],
    ["",' ✪ ','✪ america united states star '],
    ["",' ʕ•ᴥ•ʔ ','ʕ•ᴥ•ʔ cute bear animal'],
    [""," U_U ","dissapointed face disagree sad phew"],
    [""," :O ","ohhh face"],
    [""," T_T ","sad crying face tears"],
    [""," =.= ","hmm doubtful face"]
]